### PR TITLE
do not disable toggle switch buttons when auto-subscription is active (DEV-7314)

### PR DESCRIPTION
**Pull request by peter-horvath**

### CODE REVIEW

**Comment by luos** [comment]
So they can unsubscribe?

**Comment by luos** [comment]
It has a lot of logic in the click and ng-class :\

Looks OK!

**Comment by peter-horvath** [comment]
@luos This was a wrong auto-subscription logic. Auto-subscription doesn't mean that you can't change the toggle status manually like the frontend suggested previously. It means that the default status of toggles will be enabled instead of disabled. Users should still be able to disable individual toggles if they want to.

**Comment by luos** [comment]
Yeah, hm, seems weird that the frontend cared how the user was subscribed.

**Pull request merged**
